apiVersion: apps/v1
kind: Deployment
metadata:
  name: edulink-kube-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edulink-kube
  template:
    metadata:
      labels:
        app: edulink-kube
    spec:
      containers:
        - name: edulink-kube 
          image: hrushant1909/edulink-all-in-one:1.0
          ports:
            - containerPort: 5173


